// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proyectoAlkemy.Contexts;

#nullable disable

namespace proyectoAlkemy.Migrations
{
    [DbContext(typeof(DisneyContext))]
    [Migration("20220212081244_Primera")]
    partial class Primera
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("disney")
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CharactersCharactersMS", b =>
                {
                    b.Property<int>("Charactersid")
                        .HasColumnType("int");

                    b.Property<int>("movies_seriesid")
                        .HasColumnType("int");

                    b.HasKey("Charactersid", "movies_seriesid");

                    b.HasIndex("movies_seriesid");

                    b.ToTable("CharactersCharactersMS", "disney");
                });

            modelBuilder.Entity("CharactersMSMovieSerie", b =>
                {
                    b.Property<int>("Charactersid")
                        .HasColumnType("int");

                    b.Property<int>("movies_serieId")
                        .HasColumnType("int");

                    b.HasKey("Charactersid", "movies_serieId");

                    b.HasIndex("movies_serieId");

                    b.ToTable("CharactersMSMovieSerie", "disney");
                });

            modelBuilder.Entity("proyectoAlkemy.Models.Characters", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("weight")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("Characters", "disney");
                });

            modelBuilder.Entity("proyectoAlkemy.Models.CharactersMS", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("characters_ms")
                        .HasColumnType("int");

                    b.Property<int>("movie_serie")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("CharactersMs", "disney");
                });

            modelBuilder.Entity("proyectoAlkemy.Models.Genres", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("asociated_movie_serie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Genres", "disney");
                });

            modelBuilder.Entity("proyectoAlkemy.Models.MovieSerie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Genresid")
                        .HasColumnType("int");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ranking")
                        .HasColumnType("int");

                    b.Property<DateTime>("release_year")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Genresid");

                    b.ToTable("MovieSeries", "disney");
                });

            modelBuilder.Entity("CharactersCharactersMS", b =>
                {
                    b.HasOne("proyectoAlkemy.Models.Characters", null)
                        .WithMany()
                        .HasForeignKey("Charactersid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("proyectoAlkemy.Models.CharactersMS", null)
                        .WithMany()
                        .HasForeignKey("movies_seriesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharactersMSMovieSerie", b =>
                {
                    b.HasOne("proyectoAlkemy.Models.CharactersMS", null)
                        .WithMany()
                        .HasForeignKey("Charactersid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("proyectoAlkemy.Models.MovieSerie", null)
                        .WithMany()
                        .HasForeignKey("movies_serieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("proyectoAlkemy.Models.MovieSerie", b =>
                {
                    b.HasOne("proyectoAlkemy.Models.Genres", "Genres")
                        .WithMany("movies")
                        .HasForeignKey("Genresid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genres");
                });

            modelBuilder.Entity("proyectoAlkemy.Models.Genres", b =>
                {
                    b.Navigation("movies");
                });
#pragma warning restore 612, 618
        }
    }
}
